### ISSUE TITLE
How to use a local in a tag attribute?

### ISSUE THREAD

**Issue by sgilligan** [reshape/eval-code#1]
I'm trying to generate 
  `<p class="bar-suffix">test<p>`

but the following code gives me
  `<p class="bar">test</p>`

```
const reshape = require('reshape')
const expressions = require('reshape-expressions')
const evalCode = require('reshape-eval-code')

reshape({ plugins: [expressions(), evalCode({ foo: 'bar' })] })
  .process("<p class='{{ foo }}-suffix'>test</p>")
  .then((res) => {
    console.log(res.output()) // no locals required here! nice!
  })
```
Am I doing something wrong?

**Comment by sgilligan** [comment]
I can answer my own question thanks to the spike gitter channel. The suffix string is included within the eval bracketing:
```
  .process("<p class='{{foo + \"-suffix\"}}'>test</p>")
```

**Comment by jescalan** [comment]
Just released a patch that allows your original use case to work as expected 😁
